### ISSUE TITLE
Nimble

### ISSUE THREAD

**Issue by andreaferretti** [stefantalpalaru/golib-nim#1]
Hey, nice project. What is the status for it? Since the PR on Nim has been merged, I think it would be nice to have this published on Nimble, so that people can start experimenting with it

**Comment by stefantalpalaru** [comment]
Thanks.

Pull request made to add it to the Nimble database: https://github.com/nim-lang/packages/pull/266

The status is "working as advertised" and it needs additional work in the compiler to support blocking sockets in goroutines transparently and become feature complete.

**Comment by andreaferretti** [comment]
Thank you, I will try it!
