### ISSUE TITLE
invalid pragma: unchecked

### ISSUE THREAD

**Issue by narimiran** [stefantalpalaru/golib-nim#5]
I'm trying to install and test this package, but when I run `nim c src/golib.nim` on the latest Nim devel (v0.19.9), I get:

```
golib.nim(44, 25) Error: invalid pragma: unchecked
```

It seems to work on Nim v0.19.4

EDIT: from 0.19.9 changelog:

*"- The `unchecked` pragma was removed, instead use `system.UncheckedArray`."*

**Comment by stefantalpalaru** [comment]
Closed by https://github.com/stefantalpalaru/golib-nim/pull/6
